### ISSUE TITLE
What font weight I can use?

### ISSUE THREAD

**Issue by Gitbreast** [vipzhicheng/logseq-plugin-google-fonts#2]
I just figure out that "normal" and "bold" are efficient.
How can I use other weights like these?
![image](https://user-images.githubusercontent.com/96460796/183737271-a1a18fb0-78d3-4f1a-8c02-57524e44df0a.png)

PS. the three "font size" option names are typed wrong as "font color"
PSS. is it possible to just change the main text font without changing the title font?
PSSS. and perhaps add different font options for English, Chinese, Emoji, etc is useful.

**Comment by vipzhicheng** [comment]
I just released a new version. and fix a little bit.

1. typos are fixed.
2. because title was in the main text area so if you want to just change the main text. you need to set a normal font and size for title on the settings page.
3. There are so many options on the settings page now. It's too many settings if adding more.
4. For font weight, you can just use 100, 200, ..., 900, it will work.
